apiVersion: v1
kind: ConfigMap

metadata:
  name: {{ .Release.Name }}-django-config
  labels:
    app.kubernetes.io/name: scholarmate
    app.kubernetes.io/instance: {{ .Release.Name }}

data:
  DJANGO_DEBUG: {{ .Values.config.djangoDebug | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.config.djangoAllowedHosts | quote }}
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.config.databasePort | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  DATABASE_USER: {{ .Values.config.databaseUser | quote }}
  REDIS_CACHE_URL: {{ printf "redis://%s-redis:6379/1" .Release.Name | quote }}