apiVersion: v1
kind: Service

metadata:
  name: {{ .Release.Name }}-redis
  labels:
    app.kubernetes.io/name: scholarmate
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis

spec:
  type: ClusterIP

  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: redis

  ports:
    - name: redis
      port: {{ .Values.redis.service.port }}
      targetPort: {{ .Values.redis.service.targetPort }}
      protocol: TCP