deployment:
  replicas: 1

service:
  spec:
    type: LoadBalancer

ports:
  web:
    port: 8000
    exposedPort: 80

  websecure:
    port: 8443
    exposedPort: 443

providers:
  kubernetesIngress:
    enabled: true
    publishedService:
      enabled: true

ingressClass:
  enabled: true
  isDefaultClass: false

ingressRoute:
  dashboard:
    enabled: false

log:
  level: INFO