apiVersion: v1
kind: Secret

metadata:
  name: django-secret

type: Opaque

stringData:
  DJANGO_SECRET_KEY: "replace-with-django-secret-key"
  OPENAI_API_KEY: "replace-with-openai-api-key"
  SERVICE_KEY: "replace-with-service-key"
  DATABASE_PASSWORD: "replace-with-database-password"